"""A SYNTHETIC collection in the exact on-disk shape `scripts/options_pilot_collector.py` writes.

Used to exercise the recorded-replay driver and its CLI without touching any recorded market data. Everything here
is generated from a seed; no price, quote or bar corresponds to anything that happened. Files produced:

    <dir>/chain_SPY.jsonl   kind pilot_collection_chain   payload {expiration, quotes[]}
    <dir>/nbbo_SPY.jsonl    kind pilot_collection_nbbo    payload {as_of, bid, ask, sizes, source}
    <dir>/bars_SPY.jsonl    kind pilot_collection_bars    payload [bar, ...]
    <dir>/prior_bars.json   a plain list of bars, the shape the funnel's variance fit consumes

The generator can be steered to produce the conditions the audit needs: a chain snapshot that is cheap enough to
trade, one expensive enough to force WAIT, a gap in the chain across an exit window, and a quote that arrives
AFTER the instant a consumer asks for it."""
from __future__ import annotations

import json
import math
from datetime import datetime, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

ET = ZoneInfo("America/New_York")

SYMBOL = "SPY"
SESSION_OPEN = 1_789_047_000.0          # 2026-09-10T13:30:00Z = 09:30 ET, a synthetic session open
BAR_S = 60.0
CHAIN_S = 60.0
NBBO_S = 15.0
EXPIRATION = "2026-10-16"               # comfortably beyond DTE_MIN_DAYS = 21 from the session date
SPOT0 = 640.0


def _utc(e: float) -> str:
    return datetime.fromtimestamp(e, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%fZ")


def _et_naive(e: float) -> str:
    """The vendor's own convention: Eastern wall clock with no zone, milliseconds. Matches the recorded files."""
    return datetime.fromtimestamp(e, tz=ET).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3]


def _spot(i: int) -> float:
    """A deterministic, boring path. No randomness: the audit must reproduce exactly."""
    return round(SPOT0 + 0.6 * math.sin(i / 11.0) + 0.02 * i, 2)


def bar(i: int, *, t0: float = SESSION_OPEN, receipt_lag: float = 5.0) -> dict:
    ev = t0 + i * BAR_S
    c = _spot(i)
    return {"symbol": SYMBOL, "event_time": ev, "open": round(c - 0.05, 2), "high": round(c + 0.10, 2),
            "low": round(c - 0.12, 2), "close": c, "volume": 10_000 + 7 * i,
            "receipt_time": ev + BAR_S + receipt_lag, "publication_time": ev + BAR_S,
            "vwap": c, "trades": 120 + i, "provider": "SYNTHETIC_FIXTURE",
            "timestamp_convention": "event_time is the bar's opening instant, UTC epoch seconds"}


def chain_quotes(i: int, *, ask: float, strikes: int = 9, step: float = 5.0, receipt_epoch: float) -> list:
    """A small chain around the current spot. Every contract carries the SAME ask, so `ask` alone decides
    affordability and the audit does not have to reason about strike selection to force a WAIT."""
    s = _spot(i)
    atm = round(s / step) * step
    out = []
    for k in range(-(strikes // 2), strikes // 2 + 1):
        strike = atm + k * step
        for right in ("CALL", "PUT"):
            # EVERY VALUE IS A STRING and the timestamp is Eastern-naive, exactly as the recorded collection stores
            # them. A fixture in a tidier shape would not exercise the provider-boundary validation at all.
            out.append({"symbol": SYMBOL, "strike": "%.3f" % strike, "right": right, "expiration": EXPIRATION,
                        "bid": "%.2f" % (ask - 0.05), "ask": "%.2f" % ask, "bid_size": "9", "ask_size": "12",
                        "moneyness_status": "CAUSAL", "timestamp": _et_naive(receipt_epoch - 1.0)})
    return out


def write(dirpath, *, minutes: int = 60, ask: float = 4.95, prior_days: int = 6,
          chain_gap: tuple | None = None, expensive_after: int | None = None,
          expensive_ask: float = 40.0, prior_receipt_lag: float = 60.0) -> dict:
    """Write one synthetic collection.

    `chain_gap` is an (from_index, to_index) half-open range of chain snapshots to OMIT, which creates a stretch
    where no option quote is available at all. `expensive_after` switches every ask to `expensive_ask` from that
    snapshot index onward, which forces the risk envelope to refuse and the fill attempt to WAIT."""
    d = Path(dirpath)
    d.mkdir(parents=True, exist_ok=True)
    n_bars = minutes
    n_chain = int(minutes * 60.0 / CHAIN_S)
    n_nbbo = int(minutes * 60.0 / NBBO_S)

    def rec(kind, payload, receipt_epoch, provider):
        return {"kind": kind, "symbol": SYMBOL, "receipt_utc": _utc(receipt_epoch), "receipt_epoch": receipt_epoch,
                "provider": provider, "data_provenance": "SYNTHETIC_FIXTURE",
                "evidence_class": "PROSPECTIVE_OBSERVATION",
                "law": "SYNTHETIC: generated by tests/synthetic_collection.py; no market event corresponds to it",
                "payload": payload}

    # ---- bars: one record per minute carrying a small lookback window, as the collector writes them
    with (d / ("bars_%s.jsonl" % SYMBOL)).open("w") as fh:
        for i in range(n_bars):
            receipt = SESSION_OPEN + (i + 1) * BAR_S + 5.0
            window = [bar(j) for j in range(max(0, i - 4), i + 1)]
            fh.write(json.dumps(rec("pilot_collection_bars", window, receipt, "SYNTHETIC_FIXTURE")) + "\n")

    # ---- chain: one snapshot per minute
    omit = set(range(*chain_gap)) if chain_gap else set()
    with (d / ("chain_%s.jsonl" % SYMBOL)).open("w") as fh:
        for i in range(n_chain):
            if i in omit:
                continue
            receipt = SESSION_OPEN + i * CHAIN_S + 23.0
            a = expensive_ask if (expensive_after is not None and i >= expensive_after) else ask
            payload = {"expiration": EXPIRATION,
                       "quotes": chain_quotes(i, ask=a, receipt_epoch=receipt)}
            fh.write(json.dumps(rec("pilot_collection_chain", payload, receipt, "SYNTHETIC_FIXTURE")) + "\n")

    # ---- nbbo on the underlying
    with (d / ("nbbo_%s.jsonl" % SYMBOL)).open("w") as fh:
        for i in range(n_nbbo):
            t = SESSION_OPEN + i * NBBO_S + 22.0
            s = _spot(int(i * NBBO_S / BAR_S))
            payload = {"as_of": t, "available": t, "bid": round(s - 0.01, 2), "ask": round(s + 0.01, 2),
                       "bid_size": 400, "ask_size": 400, "source": "SYNTHETIC_FIXTURE:sip"}
            fh.write(json.dumps(rec("pilot_collection_nbbo", payload, t, "SYNTHETIC_FIXTURE")) + "\n")

    # ---- prior bars: the shape the funnel's variance fit consumes
    # prior_receipt_lag defaults to 60.0, which is what BULK_PULL_AVAILABILITY_V1 says availability is. A test can
    # set anything else to exercise the refusal when the artifact and the accepted formula disagree.
    prior = []
    for day in range(prior_days, 0, -1):
        t0 = SESSION_OPEN - day * 86400.0
        for i in range(390):
            prior.append(bar(i, t0=t0, receipt_lag=prior_receipt_lag - BAR_S))
    (d / "prior_bars.json").write_text(json.dumps(prior))
    return {"dir": str(d), "n_bars": n_bars, "n_chain": n_chain - len(omit), "n_nbbo": n_nbbo,
            "n_prior_bars": len(prior), "session_open_utc": _utc(SESSION_OPEN),
            "expiration": EXPIRATION, "ask": ask, "chain_gap": chain_gap, "expensive_after": expensive_after,
            "prior_receipt_lag": prior_receipt_lag}
