"""WM-0E-R3 -- replacement laboratory instruments. DEVELOPMENT ONLY.

Nothing here touches the frozen engine (DEPENDENT_BLOCK_BOOTSTRAP_V0.1,
PPW selector, B, alpha, M0, null, features, split, grading) and nothing
here is an acceptance court. controls.py (V0.1) is not edited: N3 V0 is
RETIRED there, not repaired.

N3_SHADOW_FEATURE_NULL_V1
  The retired N3 V0 deranged feature rows within train and within eval.
  That destroyed row pairing but preserved each window's realised feature
  marginals; under regime-persistent windows the frozen M0 converted the
  marginal shift into signed evaluation offsets (7/50 vs max 5 in
  COURT-V2-386a408b7417). V1 replaces permutation with a SHADOW WORLD:
    TARGET world  -> targets / resolved outcomes (the world under test)
    SHADOW world  -> observable features, generated by the SAME declared
                     process family, schema, session structure and
                     configuration class, under an INDEPENDENT seed
                     namespace and therefore an independent latent path.
  Feature autocorrelation, regime persistence and marginal evolution
  survive in distribution; the target world's causal feature linkage is
  absent by construction. The donor is a pure function of (namespace,
  target seed); target outcomes never choose it; latent identities are
  never synchronised; nothing but ObservableState crosses the boundary.

P0_POWER_CONTRACT_V1
  P0 V0 (S1 causal trend, mu = 0.0015) stays FAILED: 31/50 = 0.62 under
  honest inference, direction 50/50. The positive control is an
  instrument, so its planted-effect MAGNITUDE may be calibrated -- on a
  finite, predeclared ladder, with development seeds, under the frozen
  pipeline -- and nothing else. Selection rule predeclared below.
"""
from __future__ import annotations

import hashlib
from dataclasses import replace as _replace

from apex.world_model.canonical import content_hash
from apex.world_model.controls import ControlViolation
from apex.world_model.court import (N_STEPS, S1_PARAMS, S1_SIGMA, SEED_SET as _V0_SEEDS)
from apex.world_model.holdout import HOLDOUT_SEEDS as _CONSUMED_V21_SEEDS, derive_holdout
from apex.world_model.teststand import build_dataset
from apex.world_model.worlds import S1_CAUSAL_TREND, WorldConfig, generate_world

R3_VERSION = "WM0E_R3_CONTROL_INSTRUMENTS_V1"
SEED_MODULUS = 2 ** 31 - 1

# ---------------------------------------------------------------- retired
N3_V0_STATUS = {
    "control": "N3_FEATURE_PERMUTATION_V0",
    "status": "RETIRED_AFTER_CONTROL_FAILURE",
    "acceptance": "COURT-V2-386a408b7417: 7/50 detections, max 5",
    "reason": "within-train/within-eval row derangement destroyed direct "
              "feature-row pairing but preserved realised window-level "
              "feature marginal shifts; under regime-persistent windows the "
              "frozen M0 converted them into signed evaluation offsets",
    "edited": False, "rerun": False}
P0_V0_STATUS = {
    "control": "P0_CAUSAL_TREND_V0", "planted_mu": S1_PARAMS["mu"],
    "status": "FAIL_POWER_REQUIREMENT",
    "acceptance": "COURT-V2-386a408b7417: 31/50 = 0.62 (required 0.80); "
                  "direction 50/50",
    "interpretation": "the causal relationship existed consistently but was "
                      "under-powered relative to the frozen dependence-aware "
                      "court and the registered 80% requirement",
    "requirement_lowered": False, "bootstrap_altered": False,
    "M0_retuned": False, "horizon_changed": False}

# ---------------------------------------------------------------- N3 V1
N3_V1 = "N3_SHADOW_FEATURE_NULL_V1"
SHADOW_NAMESPACE = "WM0E_R3_N3_SHADOW_V1"


def shadow_seed(target_seed: int) -> int:
    """Deterministic donor seed from the namespace and the TARGET seed
    only. Refuses the degenerate case of landing on the target itself."""
    h = hashlib.sha256(("%s|%d" % (SHADOW_NAMESPACE, target_seed)).encode()).digest()
    s = int.from_bytes(h[:8], "big") % SEED_MODULUS
    if s == target_seed:
        raise ControlViolation("shadow seed collided with target seed %d" % target_seed)
    return s


def shadow_world(target_world):
    """Same declared family/config class as the target; only the seed
    (hence the latent path) differs. Fails closed on same-world pairing."""
    cfg = target_world.config
    sh = generate_world(_replace(cfg, seed=shadow_seed(cfg.seed)))
    if sh.world_hash == target_world.world_hash or sh.config.seed == cfg.seed:
        raise ControlViolation("shadow world is the target world")
    if sh.world_type != target_world.world_type:
        raise ControlViolation("shadow world family differs from target")
    return sh


def n3_v1_dataset(seed: int):
    """The ONE seam: observable features from the SHADOW world, targets and
    outcome records from the TARGET world, same split, same subject."""
    def build(world, subject, split):
        if world.config.seed != seed:
            raise ControlViolation("N3 V1 dataset built for seed %d, got world seed %d"
                                   % (seed, world.config.seed))
        sh = shadow_world(world)
        Xtr_s, _, itr_s, _ = build_dataset(sh, subject, split.train_steps)
        Xev_s, _, iev_s, _ = build_dataset(sh, subject, split.eval_steps)
        _, ytr, itr, _ = build_dataset(world, subject, split.train_steps)
        _, yev, iev, ev_out = build_dataset(world, subject, split.eval_steps)
        if itr_s != itr or iev_s != iev:
            raise ControlViolation("shadow and target step indices diverge")
        return Xtr_s, ytr, Xev_s, yev, iev, ev_out
    return build


def n3_v1_identity(target_world) -> str:
    sh = shadow_world(target_world)
    return content_hash({"control": N3_V1, "namespace": SHADOW_NAMESPACE,
                         "target_world_hash": target_world.world_hash,
                         "shadow_world_hash": sh.world_hash})


N3_V1_CONTRACT = {
    "name": N3_V1, "replaces": "N3_FEATURE_PERMUTATION_V0 (retired, not edited)",
    "construction": "features <- independent shadow world of the same declared "
                    "family/config; targets <- target world; same split/subject",
    "destroys": "the target world's causal feature->target linkage",
    "preserves": "feature serial dependence, regime persistence and marginal "
                 "evolution (in distribution); target temporal structure",
    "donor_rule": "shadow seed = sha256(%s|target_seed)[:8] mod 2^31-1; never "
                  "chosen from outcomes; latent identities never synchronised"
                  % SHADOW_NAMESPACE,
    "boundary": "only ObservableState crosses; generator truth of either world "
                "never reaches model input",
    "expected": "NO_SIGNAL"}

# ---------------------------------------------------------------- P0 V1
P0_V1 = "P0_POWER_CONTRACT_V1"
P0_BASE_MU = S1_PARAMS["mu"]
P0_POWER_LADDER = (1.0, 1.5, 2.0, 3.0)          # FINITE. Predeclared. Not extended.
P0_V1_SELECTION = {"min_detection_rate": 0.90,
                   "min_wilson95_lower": 0.80,
                   "min_direction_rate": 0.95,
                   "rule": "the SMALLEST ladder level satisfying all three; "
                           "none -> STOP (no extension, no lowering)"}
P0_V1_FUTURE_ACCEPTANCE = {"min_detections": 40, "min_direction": 45, "n": 50,
                           "note": "unchanged from V0; the development margin is "
                                   "deliberately wider than the acceptance rule"}


def p0_world(seed: int, multiplier: float):
    if multiplier not in P0_POWER_LADDER:
        raise ControlViolation("effect level %r is not on the predeclared ladder"
                               % multiplier)
    params = dict(S1_PARAMS); params["mu"] = P0_BASE_MU * multiplier
    return generate_world(WorldConfig(world_type=S1_CAUSAL_TREND, seed=seed,
                                      n_subjects=1, n_steps=N_STEPS,
                                      sigma=S1_SIGMA, params=params,
                                      observe_latent=True))


# ---------------------------------------------------------------- dev seeds
N3_DEV_NAMESPACE = "WM0E_R3_N3_DEV_V0"
P0_DEV_NAMESPACE = "WM0E_R3_P0_DEV_V0"
N3_V1_DEV_CELLS = 100
N3_V1_DEV_MAX_FP = 5
P0_DEV_SEEDS_PER_LEVEL = 50
_EXCLUDED_BASE = tuple(_V0_SEEDS) + tuple(_CONSUMED_V21_SEEDS)
N3_DEV = derive_holdout(N3_DEV_NAMESPACE, N3_V1_DEV_CELLS, _EXCLUDED_BASE)
N3_DEV_SEEDS = tuple(N3_DEV["seeds"])
P0_DEV = derive_holdout(P0_DEV_NAMESPACE, P0_DEV_SEEDS_PER_LEVEL,
                        _EXCLUDED_BASE + N3_DEV_SEEDS)
P0_DEV_SEEDS = tuple(P0_DEV["seeds"])
assert not set(N3_DEV_SEEDS) & set(_EXCLUDED_BASE)
assert not set(P0_DEV_SEEDS) & (set(_EXCLUDED_BASE) | set(N3_DEV_SEEDS))


def predeclaration() -> dict:
    """Everything fixed BEFORE any development result exists."""
    return {"version": R3_VERSION, "acceptance_court": "NONE in this brick",
            "new_acceptance_seeds_created": False,
            "frozen_engine": "DEPENDENT_BLOCK_BOOTSTRAP_V0.1 (contract hash "
                             "recorded by the runner)",
            "N3_V0": N3_V0_STATUS, "N3_V1": N3_V1_CONTRACT,
            "N3_V1_development": {"cells": N3_V1_DEV_CELLS, "alpha": 0.025,
                                  "max_false_detections": N3_V1_DEV_MAX_FP,
                                  "seed_namespace": N3_DEV_NAMESPACE,
                                  "seed_set_hash": N3_DEV["seed_set_hash"],
                                  "excluded": "V0 dev 25 + consumed V2.1 50",
                                  "stop_rule": "> 5/100 -> STOP; no redesign "
                                               "inside this identity"},
            "P0_V0": P0_V0_STATUS,
            "P0_V1": {"family": "S1_CAUSAL_TREND, only mu scaled",
                      "base_mu": P0_BASE_MU, "ladder": list(P0_POWER_LADDER),
                      "seeds_per_level": P0_DEV_SEEDS_PER_LEVEL,
                      "seed_namespace": P0_DEV_NAMESPACE,
                      "seed_set_hash": P0_DEV["seed_set_hash"],
                      "selection": P0_V1_SELECTION,
                      "future_acceptance": P0_V1_FUTURE_ACCEPTANCE,
                      "what_this_is": "POSITIVE_CONTROL_POWER_CALIBRATION, not "
                                      "model tuning; M0/horizon/inference frozen"},
            "seed_sets_disjoint": True}


def predeclaration_hash() -> str:
    return content_hash(predeclaration())
