"""Fail-closed data-source admission for World Model research.

THE THREAT THIS ACTUALLY DEFENDS AGAINST
Not malice. The realistic failure is a researcher -- human or agent --
reaching for the nearest convenient file. `/apex-data/core/btc/
window_outcomes.jsonl` is RIGHT THERE and it is exactly the shape a
label wants. One import and the World Model has been fitted on resolved
prospective outcomes, and no result it ever produces can be trusted
again. That contamination is unfalsifiable after the fact: you cannot
un-see a label.

WHY THE CALLER'S LABEL GRANTS NOTHING
An enum where the caller writes source_class=SYNTHETIC_FIXTURE while
handing over a real outcomes file is security theatre. So the declared
class is treated as a REQUEST, never as evidence. Admission is decided
by the artifact:

  1. the authority contract must be intact                (authority.py)
  2. the declared class must be one of the three permitted
  3. the path, FULLY RESOLVED (symlinks, .., mounts), must not land
     inside any real-evidence root -- this check runs regardless of what
     the caller declared, and it is the one that matters
  4. it must land inside the fixture root
  5. it must be listed in that root's _PROVENANCE.json under its own
     sha256

Step 3 is deliberately independent of step 2. A caller who declares
SYNTHETIC_FIXTURE and passes the BTC outcomes ledger is refused by the
path, not by the label.

HONEST LIMITATION -- STATED, NOT HIDDEN
This is a PROVENANCE boundary, not a sandbox. A determined actor who
copies a real ledger into the fixture root AND writes a matching
_PROVENANCE.json entry defeats it. That is a deliberate multi-step
forgery, not an accident or a moment of convenience, and it is the
strongest practical boundary at this stage without OS-level isolation.
CALLER_METADATA_SPOOF_RESISTANCE is therefore reported as PARTIAL, and
should stay PARTIAL until the fixtures are generated by a signed
generator whose output this module verifies.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

from apex.world_model.authority import (WorldModelAuthorityViolation,
                                        assert_authority)

SOURCE_CONTRACT = "WORLD_MODEL_SOURCE_BOUNDARY_V0"

PERMITTED_SOURCE_CLASSES = frozenset({
    "SYNTHETIC_FIXTURE", "NULL_FIXTURE", "MANUAL_FIXTURE"})

# Named so a refusal says WHICH prohibition was hit, not just "denied".
FORBIDDEN_SOURCE_CLASSES = frozenset({
    "REAL_HISTORICAL_LABEL", "REAL_PROSPECTIVE_OUTCOME",
    "BOOK_PNL", "REAL_EXECUTION_RESULT"})

# Every location APEX keeps real market evidence, book state or
# prospective outcomes. Deny is by RESOLVED path prefix, so a symlink or
# a ../.. traversal cannot walk out of the fixture root into one of
# these.
REAL_EVIDENCE_ROOTS = (
    "/apex-data/core/btc",
    "/apex-data/core/intraday",
    "/apex-data/core/edgeforge",
    "/apex-data/core/equities",
    "/apex-data/core/live",
    "/apex-data/core/historical",
    "/apex-data/core/capital",
    "/apex-data/core/catalyst",
    "/apex-data/core/crypto",
    "/apex-data/core/ops",
    "/apex-data/core/heartbeats",
    "/apex-data/core/equity_fabric_rth_profile",
    "/apex-data/core/equity_fabric_validation_profile",
    "/apex-data/runtime/data/live",
    "/apex-data/history-a",
    "/apex-data/history-b",
    "/opt/apex-repo/results",
    "/opt/apex/releases",
)

FIXTURE_ROOT = Path("/apex-research/world-model-fixtures")
PROVENANCE_FILE = "_PROVENANCE.json"


class SourceAdmissionRefused(Exception):
    """A data source was refused. There is no override, no force flag,
    and no environment variable: a bypass switch is just a slower way of
    having no boundary."""


def _resolved(p) -> Path:
    """Fully resolve before ANY decision. strict=False so a
    non-existent path still resolves its parents -- we must be able to
    refuse a path that does not exist yet."""
    return Path(p).expanduser().resolve(strict=False)


def real_evidence_root_for(path) -> str | None:
    """Which real-evidence root this path falls under, if any."""
    rp = _resolved(path)
    for root in REAL_EVIDENCE_ROOTS:
        rr = _resolved(root)
        if rp == rr or rr in rp.parents:
            return str(rr)
    return None


def sha256_of(path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def admit(path, *, declared_class: str, manifest: dict | None = None,
          fixture_root: Path | None = None) -> dict:
    """Admit a data source, or refuse with a named reason.

    `declared_class` is a REQUEST. It is checked, but it never overrides
    what the artifact itself says.
    """
    try:
        assert_authority(manifest)
    except WorldModelAuthorityViolation as e:
        raise SourceAdmissionRefused(
            "AUTHORITY_INVALID: %s" % e) from e

    # ---- the declared class is checked, and grants nothing ----------
    if declared_class in FORBIDDEN_SOURCE_CLASSES:
        raise SourceAdmissionRefused(
            "FORBIDDEN_SOURCE_CLASS: %s is forbidden under %s. This "
            "package may not read real labels, resolved prospective "
            "outcomes, book P&L or execution results."
            % (declared_class, SOURCE_CONTRACT))
    if declared_class not in PERMITTED_SOURCE_CLASSES:
        raise SourceAdmissionRefused(
            "UNKNOWN_SOURCE_CLASS: %r. Permitted: %s. An unrecognised "
            "class is refused rather than defaulted -- defaulting is how "
            "a boundary becomes decorative."
            % (declared_class, ", ".join(sorted(PERMITTED_SOURCE_CLASSES))))

    # ---- the artifact decides, not the label ------------------------
    rp = _resolved(path)
    hit = real_evidence_root_for(rp)
    if hit:
        raise SourceAdmissionRefused(
            "REAL_EVIDENCE_PATH: %s resolves inside %s, which holds real "
            "market evidence, prospective outcomes or book state. The "
            "declared class %r does not change what the file IS."
            % (rp, hit, declared_class))

    root = _resolved(fixture_root or FIXTURE_ROOT)
    if not (rp == root or root in rp.parents):
        raise SourceAdmissionRefused(
            "OUTSIDE_FIXTURE_ROOT: %s is not under %s. Research data "
            "must come from the fixture root; anything else is refused "
            "even if it is harmless." % (rp, root))

    if not rp.exists():
        raise SourceAdmissionRefused("MISSING_SOURCE: %s" % rp)

    prov_path = root / PROVENANCE_FILE
    if not prov_path.exists():
        raise SourceAdmissionRefused(
            "NO_PROVENANCE_MANIFEST: %s absent. A file appearing in the "
            "fixture root is not thereby a fixture." % prov_path)
    try:
        prov = json.loads(prov_path.read_text())
    except (OSError, json.JSONDecodeError) as e:
        raise SourceAdmissionRefused(
            "PROVENANCE_UNREADABLE: %s" % e) from e

    entries = prov.get("fixtures") or {}
    key = str(rp.relative_to(root))
    rec = entries.get(key)
    if rec is None:
        raise SourceAdmissionRefused(
            "UNDECLARED_FIXTURE: %s is not listed in %s. Copying a file "
            "into the fixture root does not make it a fixture."
            % (key, PROVENANCE_FILE))
    actual = sha256_of(rp)
    if rec.get("sha256") != actual:
        raise SourceAdmissionRefused(
            "PROVENANCE_HASH_MISMATCH: %s declares %s but the file is "
            "%s -- the content changed after it was declared."
            % (key, str(rec.get("sha256"))[:16], actual[:16]))
    if rec.get("source_class") != declared_class:
        raise SourceAdmissionRefused(
            "PROVENANCE_CLASS_MISMATCH: caller declared %r but the "
            "provenance record says %r. The record wins."
            % (declared_class, rec.get("source_class")))

    return {"contract": SOURCE_CONTRACT, "path": str(rp),
            "source_class": rec["source_class"], "sha256": actual,
            "admitted": True,
            "generator": rec.get("generator", "UNDECLARED")}
